### ISSUE TITLE
How to navigate through directories inside archive

### ISSUE THREAD

**Issue by kickthemooon** [thephpleague/flysystem-ziparchive#13]
Example:

example.zip
--| dir
----| file.jpg
----| file.jpg
----| file.jpg

I would like to open a directory inside a zip file and iterate over the files inside it, but im not sure how?

**Comment by frankdejonge** [comment]
Hi,

You can use the listContents function to do that.

**Comment by JoshuaBehrens** [comment]
Unfortunately the issue is that directories are not existing per sé in zip files. A simple case can be created using `zip -r archive directory/file`. All files are listed with `listContents` of the adapter without the matter of regarding the recursive flag. Later on flysystem will filter the unwanted entries out of the list (`isEntryOutOfScope`). This way I will never see the entry with the type directory as none is every provided :/ I attached a test case.
[archive.zip](https://github.com/thephpleague/flysystem-ziparchive/files/5732313/archive.zip)
